### ISSUE TITLE
Docker container for the backend does not run 

### ISSUE THREAD

**Issue by jefkine** [diicellman/dspy-gradio-rag#1]
Hi,

The docker container associated with the backed at port 8000 exits with status code 1. The Phoenix container runs successfully

see dump here

--------------------------------------------

Attaching to dspy-gradio-rag-backend-1, dspy-gradio-rag-phoenix-1
dspy-gradio-rag-backend-1  | Traceback (most recent call last):
dspy-gradio-rag-backend-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
dspy-gradio-rag-backend-1  |     yield
dspy-gradio-rag-backend-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 233, in handle_request
dspy-gradio-rag-backend-1  |     resp = self._pool.handle_request(req)
dspy-gradio-rag-backend-1  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
dspy-gradio-rag-backend-1  |     raise exc from None
dspy-gradio-rag-backend-1  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
dspy-gradio-rag-backend-1  |     response = connection.handle_request(
dspy-gradio-rag-backend-1  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
dspy-gradio-rag-backend-1  |     raise exc
dspy-gradio-rag-backend-1  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
dspy-gradio-rag-backend-1  |     stream = self._connect(request)
dspy-gradio-rag-backend-1  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 122, in _connect
dspy-gradio-rag-backend-1  |     stream = self._network_backend.connect_tcp(**kwargs)
dspy-gradio-rag-backend-1  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
dspy-gradio-rag-backend-1  |     with map_exceptions(exc_map):
dspy-gradio-rag-backend-1  |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
dspy-gradio-rag-backend-1  |     self.gen.throw(typ, value, traceback)
dspy-gradio-rag-backend-1  |   File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
dspy-gradio-rag-backend-1  |     raise to_exc(exc) from exc
dspy-gradio-rag-backend-1  | httpcore.ConnectError: [Errno 111] Connection refused
dspy-gradio-rag-backend-1  | 
dspy-gradio-rag-backend-1  | The above exception was the direct cause of the following exception:
dspy-gradio-rag-backend-1  | 
dspy-gradio-rag-backend-1  | Traceback (most recent call last):
dspy-gradio-rag-backend-1  |   File "/rag/main.py", line 14, in <module>
dspy-gradio-rag-backend-1  |     from app.gradio_ui.ui import gradio_iface
dspy-gradio-rag-backend-1  |   File "/rag/app/gradio_ui/ui.py", line 2, in <module>
dspy-gradio-rag-backend-1  |     from app.gradio_ui.zero_shot_ui import zero_shot
dspy-gradio-rag-backend-1  |   File "/rag/app/gradio_ui/zero_shot_ui.py", line 21, in <module>
dspy-gradio-rag-backend-1  |     get_list_ollama_models(),
dspy-gradio-rag-backend-1  |   File "/rag/app/utils/rag_functions.py", line 148, in get_list_ollama_models
dspy-gradio-rag-backend-1  |     models_list = client.list()
dspy-gradio-rag-backend-1  |   File "/usr/local/lib/python3.10/site-packages/ollama/_client.py", line 328, in list
dspy-gradio-rag-backend-1  |     return self._request('GET', '/api/tags').json()
dspy-gradio-rag-backend-1  |   File "/usr/local/lib/python3.10/site-packages/ollama/_client.py", line 68, in _request
dspy-gradio-rag-backend-1  |     response = self._client.request(method, url, **kwargs)
dspy-gradio-rag-backend-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 827, in request
dspy-gradio-rag-backend-1  |     return self.send(request, auth=auth, follow_redirects=follow_redirects)
dspy-gradio-rag-backend-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 914, in send
dspy-gradio-rag-backend-1  |     response = self._send_handling_auth(
dspy-gradio-rag-backend-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 942, in _send_handling_auth
dspy-gradio-rag-backend-1  |     response = self._send_handling_redirects(
dspy-gradio-rag-backend-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
dspy-gradio-rag-backend-1  |     response = self._send_single_request(request)
dspy-gradio-rag-backend-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1015, in _send_single_request
dspy-gradio-rag-backend-1  |     response = transport.handle_request(request)
dspy-gradio-rag-backend-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 232, in handle_request
dspy-gradio-rag-backend-1  |     with map_httpcore_exceptions():
dspy-gradio-rag-backend-1  |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
dspy-gradio-rag-backend-1  |     self.gen.throw(typ, value, traceback)
dspy-gradio-rag-backend-1  |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
dspy-gradio-rag-backend-1  |     raise mapped_exc(message) from exc
dspy-gradio-rag-backend-1  | httpx.ConnectError: [Errno 111] Connection refused
dspy-gradio-rag-backend-1 exited with code 1

**Comment by kailust** [comment]
How did you get that far? I couldnt even get it to build, i had ollama running too and updated the address in compose.yml

ERROR: failed to solve: process "python -m app.utils.load" did not complete successfully: exit code: 1
ERROR: Service 'backend' failed to build : Build failed

**Comment by diicellman** [comment]
The problem was with backend's Dockerfile. I didn't declare environment variables with the ARG directive. Also when you running the app in containers you need to host your Ollama on `0.0.0.0` here's the [guide](https://github.com/ollama/ollama/blob/main/docs/faq.md) on how to do it.

**Comment by jefkine** [comment]
Thanks @diicellman. Also, running a docker container that shares the host's network stack works but has the downside of removing the isolation layer between the container and the host machine's network.
